### ISSUE TITLE
Content rendering is hiding the title and first lines

### ISSUE THREAD

**Issue by evankanderson** [knative/website#118]
See https://knative.dev/contributing/mechanics/feature-tracks/ for an example.

![Screen Shot 2020-01-02 at 14 18 41](https://user-images.githubusercontent.com/7959095/71696813-da459d00-2d6a-11ea-8cc6-9831e65df49f.png)

**Comment by evankanderson** [comment]
This seems to be due to the following CSS:

```css
@media (min-width: 768px)
.td-navbar {
    position: fixed; /* This causes the navbar not to take any space at the top of the page */
    top: 0;
    width: 100%;
}
```

We may need something that adds a margin to the top of the page when the page is wider than 768px.
